import JSZip from 'jszip';
import axios from 'axios';
import { getFileExtension, sanitizeFilename, getDomainFromUrl } from './utils';
import type { DownloadableIcon } from '@/types/favicon';
import { appConfig } from '@/config';

// Backend API base URL - from centralized config
const API_BASE_URL = appConfig.apiUrl;

/**
 * Download icon via backend proxy to avoid CORS issues
 */
async function fetchIconBlob(iconUrl: string): Promise<Blob> {
  try {
    // Use backend proxy endpoint to avoid CORS issues
    const proxyUrl = `${API_BASE_URL}/api/proxy/icon?url=${encodeURIComponent(iconUrl)}`;
    const response = await axios.get(proxyUrl, {
      timeout: 30000,
      responseType: 'blob',
    });
    return response.data;
  } catch (error) {
    console.error(`Failed to fetch icon from ${iconUrl}:`, error);
    throw error;
  }
}

/**
 * Download a single icon file
 */
export async function downloadSingleIcon(
  icon: DownloadableIcon,
  websiteUrl: string
): Promise<void> {
  try {
    const blob = await fetchIconBlob(icon.href);
    const extension = getFileExtension(icon.href, icon.type);
    const domain = getDomainFromUrl(websiteUrl);
    const size = icon.size || icon.sizes || 'unknown';
    const filename = sanitizeFilename(`${domain}_${icon.source}_${size}.${extension}`);

    // Create download link
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  } catch (error) {
    console.error('Failed to download icon:', error);
    throw new Error('Failed to download icon. Please try again.');
  }
}

/**
 * Download all icons as a ZIP file
 */
export async function downloadAllIconsAsZip(
  icons: DownloadableIcon[],
  websiteUrl: string,
  onProgress?: (current: number, total: number) => void
): Promise<void> {
  const zip = new JSZip();
  const domain = getDomainFromUrl(websiteUrl);
  const folderName = `${domain}_favicons`;
  const folder = zip.folder(folderName);

  if (!folder) {
    throw new Error('Failed to create ZIP folder');
  }

  let completed = 0;
  const total = icons.length;

  // Download each icon and add to ZIP
  const downloadPromises = icons.map(async (icon, index) => {
    try {
      const blob = await fetchIconBlob(icon.href);
      const extension = getFileExtension(icon.href, icon.type);
      const size = icon.size || icon.sizes || 'unknown';

      // Create unique filename for each icon
      const filename = sanitizeFilename(`${index + 1}_${icon.source}_${size}.${extension}`);

      folder.file(filename, blob);

      completed++;
      if (onProgress) {
        onProgress(completed, total);
      }
    } catch (error) {
      console.error(`Failed to download icon ${icon.href}:`, error);
      // Continue with other icons even if one fails
    }
  });

  await Promise.all(downloadPromises);

  // Add a README file with metadata
  const readme = generateReadme(icons, websiteUrl, domain);
  folder.file('README.txt', readme);

  // Generate ZIP file
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6,
    },
  });

  // Download ZIP file
  const url = window.URL.createObjectURL(zipBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${domain}_favicons.zip`;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
}

/**
 * Generate README content for the ZIP file
 */
function generateReadme(icons: DownloadableIcon[], websiteUrl: string, domain: string): string {
  const date = new Date().toLocaleDateString();
  const time = new Date().toLocaleTimeString();

  let content = `Favicon Collection for ${domain}\n`;
  content += `${'='.repeat(50)}\n\n`;
  content += `Extracted from: ${websiteUrl}\n`;
  content += `Date: ${date} ${time}\n`;
  content += `Total icons: ${icons.length}\n\n`;
  content += `File List:\n`;
  content += `${'-'.repeat(50)}\n\n`;

  icons.forEach((icon, index) => {
    const extension = getFileExtension(icon.href, icon.type);
    const size = icon.size || icon.sizes || 'unknown';
    const filename = sanitizeFilename(`${index + 1}_${icon.source}_${size}.${extension}`);

    content += `${index + 1}. ${filename}\n`;
    content += `   Size: ${icon.displaySize}\n`;
    content += `   Source: ${icon.source}\n`;
    content += `   Type: ${icon.type || 'unknown'}\n`;
    if (icon.rel) {
      content += `   Rel: ${icon.rel}\n`;
    }
    content += `   URL: ${icon.href}\n\n`;
  });

  content += `\n${'-'.repeat(50)}\n`;
  content += `Generated by Favicon Extractor\n`;
  content += `https://github.com/yourusername/favicon-extractor\n`;

  return content;
}

/**
 * Copy icon URL to clipboard
 */
export async function copyIconUrl(url: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(url);
  } catch (error) {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = url;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
  }
}
